### PR TITLE
Update Loculus version to c723c5

### PR DESCRIPTION
**Pull request by corneliusroemer**
@corneliusroemer wants to update the Loculus version from https://github.com/loculus-project/loculus/commit/188eb04e7cca97619b9d5bd048782d20ac196f55 to https://github.com/loculus-project/loculus/commit/c723c562ed2ca4a0252b3899fd375dab9a652c5a.

### Changelog
- loculus-project/loculus#2975
- loculus-project/loculus#2971
- loculus-project/loculus#2958
- loculus-project/loculus#2969
- loculus-project/loculus#2968

### Comparison
https://github.com/loculus-project/loculus/compare/188eb04e7cca97619b9d5bd048782d20ac196f55...c723c562ed2ca4a0252b3899fd375dab9a652c5a

### Preview
https://preview-update-loculus-c723c5.pathoplexus.org

### CODE REVIEW

**Comment by corneliusroemer** [comment]
Triggered by https://github.com/loculus-project/loculus/pull/2979

But it seems to have incorrectly passed the sha arguments unfortunately

**Review by theosanderson — DISMISSED** [review]

**Comment by corneliusroemer** [comment]
While I triggered this as part of testing actions, no reason not to release the latest changes I think @theosanderson

**Review by theosanderson — APPROVED** [review]

**Comment by corneliusroemer** [comment]
I merged the config updates required due to breaking config change https://github.com/pathoplexus/pathoplexus/pull/225 - will wait for the preview before merging - just to check it all looks good

**Comment by theosanderson** [comment]
Ooh yeah, a nice indication that marking breaking changes is good (ofc we didn't have a policy before) - I wouldn't have realised.

**Comment by corneliusroemer** [comment]
Looking good now:
image

**Pull request merged**
