### PR TITLE
Breaking: Update Loculus version to 0fdac5

### PR DESCRIPTION
**Pull request by corneliusroemer**
@corneliusroemer wants to update the Loculus version from https://github.com/loculus-project/loculus/commit/437d484a102ca8d2ae09f2e60fb6c0785b5ed154 to https://github.com/loculus-project/loculus/commit/0fdac51a1db9357bf24267e824307b0b026b715d.

### Notable changes (selection)

- loculus-project/loculus#3263
- loculus-project/loculus#3279
- loculus-project/loculus#3272
- loculus-project/loculus#3259
- loculus-project/loculus#3232
- loculus-project/loculus#3246
- loculus-project/loculus#3223

### Changelog (full)
- loculus-project/loculus#3263
- loculus-project/loculus#3279
- loculus-project/loculus#3319
- loculus-project/loculus#3318
- loculus-project/loculus#3312
- loculus-project/loculus#3313
- loculus-project/loculus#3309
- loculus-project/loculus#3310
- loculus-project/loculus#3303
- loculus-project/loculus#3104
- loculus-project/loculus#3302
- loculus-project/loculus#3272
- loculus-project/loculus#3297
- loculus-project/loculus#3289
- loculus-project/loculus#3286
- loculus-project/loculus#3291
- loculus-project/loculus#3292
- loculus-project/loculus#3290
- loculus-project/loculus#3287
- loculus-project/loculus#3277
- loculus-project/loculus#3259
- loculus-project/loculus#3276
- loculus-project/loculus#3232
- loculus-project/loculus#3246
- loculus-project/loculus#3247
- loculus-project/loculus#3257
- loculus-project/loculus#3255
- loculus-project/loculus#3223
- loculus-project/loculus#3234
- loculus-project/loculus#3236
- loculus-project/loculus#3196
- loculus-project/loculus#3230
- loculus-project/loculus#3231

### Comparison
https://github.com/loculus-project/loculus/compare/437d484a102ca8d2ae09f2e60fb6c0785b5ed154...0fdac51a1db9357bf24267e824307b0b026b715d

### Preview
https://preview-update-loculus-0fdac5.pathoplexus.org

### CODE REVIEW

**Comment by corneliusroemer** [comment]
The prepro changes are actually breaking - we need to repreprocess. Sorry for forgetting about this. @fengelniederhammer pinging you as you will face similar issues for Genspectrum.

**Comment by anna-parker** [comment]
Potential values.yaml changes in https://github.com/loculus-project/loculus/pull/3223,

**Comment by corneliusroemer** [comment]
Ah, actually the prepro changes aren't breaking as we just introduce _new_ features, not removing old ones or changing them!

**Comment by corneliusroemer** [comment]
> Potential values.yaml changes in https://github.com/loculus-project/loculus/pull/3223,

These seem backwards compatible as defaults are set - but it's safer to add the defaults here to be explicit.

**Comment by corneliusroemer** [comment]
I think I won't use the date range prepro functions here until we have the search UI ready to go along with it.

**Comment by fengelniederhammer** [comment]
> The prepro changes are actually breaking

Which changes are you refering to?

**Comment by corneliusroemer** [comment]
>> The prepro changes are actually breaking

> Which changes are you refering to?

New processing functions that allow parsing dates into ranges. I was wrong about them being breaking, they aren't. And we're not using the feature here yet, I can notify you when we really _are_ making those changes in a future PR here.

**Pull request merged**
