### PR TITLE
Update Loculus version to 281b6e

### PR DESCRIPTION
**Pull request by corneliusroemer**
@theosanderson wants to update the Loculus version from https://github.com/loculus-project/loculus/commit/2849151a62e32c4a16819eb2daae8f72fa22beab to https://github.com/loculus-project/loculus/commit/281b6e8636bdbfcdfec66f0fc08e71fc938fe27e.

Preview: https://preview-update-loculus-281b6e.pathoplexus.org/

### 🚨 Breaking Changes
- loculus-project/loculus#3028
- loculus-project/loculus#3212
- loculus-project/loculus#3213
- loculus-project/loculus#3166
- loculus-project/loculus#3163

### Changelog
- loculus-project/loculus#3207
- loculus-project/loculus#3028
- loculus-project/loculus#3220
- loculus-project/loculus#3222
- loculus-project/loculus#3221
- loculus-project/loculus#3219
- loculus-project/loculus#3184
- loculus-project/loculus#3212
- loculus-project/loculus#3216
- loculus-project/loculus#3213
- loculus-project/loculus#3125
- loculus-project/loculus#3206
- loculus-project/loculus#3202
- loculus-project/loculus#3150
- loculus-project/loculus#3193
- loculus-project/loculus#3188
- loculus-project/loculus#3190
- loculus-project/loculus#3186
- loculus-project/loculus#3075
- loculus-project/loculus#3183
- loculus-project/loculus#3181
- loculus-project/loculus#3156
- loculus-project/loculus#3178
- loculus-project/loculus#3062
- loculus-project/loculus#3083
- loculus-project/loculus#3173
- loculus-project/loculus#3175
- loculus-project/loculus#3168
- loculus-project/loculus#3166
- loculus-project/loculus#3165
- loculus-project/loculus#3163
- loculus-project/loculus#3159
- loculus-project/loculus#3157
- loculus-project/loculus#3149

### Comparison
https://github.com/loculus-project/loculus/compare/2849151a62e32c4a16819eb2daae8f72fa22beab...281b6e8636bdbfcdfec66f0fc08e71fc938fe27e

### Preview
https://preview-update-loculus-281b6e.pathoplexus.org

### CODE REVIEW

**Comment by theosanderson** [comment]
Huh the CI for breaking changes hasn't spotted the one here

**Comment by anna-parker** [comment]
We also need to add the changes in https://github.com/loculus-project/loculus/pull/3181/files and https://github.com/loculus-project/loculus/pull/3028

**Comment by theosanderson** [comment]
It looks like we definitely need changes for https://github.com/loculus-project/loculus/pull/3166 (adding the same file in PP)

**Comment by theosanderson** [comment]
https://github.com/loculus-project/loculus/pull/3212 does look like we still need to do something?

**Review by theosanderson — APPROVED** [review]
lgtm though we'll want to test thoroughly in staging

**Comment by theosanderson** [comment]
(thanks @anna-parker ! quite a changelog!)

**Pull request merged**
