### PR TITLE
chore: include file-downloads & outlinks in plausible config

### PR DESCRIPTION
**Pull request by corneliusroemer**
For the non-production sites we might want to set up an extra domain if we wanted to also keep track of them (for now possibly best to only use production, as otherwise we count a lot of dev traffic)

### CODE REVIEW

**Review by theosanderson — CHANGES_REQUESTED** [review]
I just learnt we can track specifically by subdomain on Plausible :) 
image

https://plausible.io/docs/subdomain-hostname-filter

**Comment by theosanderson** [comment]
(Downloads would be really useful though!)

**Comment by corneliusroemer** [comment]
Here we go

**Review by theosanderson — APPROVED** [review]
Thanks!!

**Pull request merged**
