### PR TITLE
Increase muffet timeout again

### PR DESCRIPTION
**Pull request by theosanderson**
This goes back to my original commit from https://github.com/pathoplexus/pathoplexus/pull/187 as, for whatever reason, what's on main isn't working. Also it seems to include some internal links in external? https://github.com/pathoplexus/pathoplexus/actions/runs/11111325516/job/30871119683

### CODE REVIEW

**Comment by theosanderson** [comment]
Closing for now - the issue with main is insufficient LAPIS memory

**Comment by corneliusroemer** [comment]
It's not possible to only test external links, external is a superset of
internal.

**Comment by theosanderson** [comment]
hmm - then I'd really not split them out (and if we did, name them appropriately)

**Comment by corneliusroemer** [comment]
the splitting is so that we have more and less flaky actions. happy to rename: internal-only, external-also?

**Pull request closed without merging**
