### PR TITLE
feat: add broken-link-checker gh action and fix broken links

### LINKED ISSUE #133: [BUG] Summary of General Assembly Meeting not available
Link to
https://pathoplexus.org/about/governance/minutes/2024-08-12_GAmeeting.pdf
failes.
Screenshot_2024-09-14-18-59-40-03_3aea4af51f236e4932235fdada7d1643

### LINKED ISSUE #136: Fix broken links
At least the following links appear to be broken at the moment:

The unindented link is the page on which the error is. The indented one with status code is the broken target:

```
https://preview-broken-link-action.pathoplexus.org/news
	404	https://preview-broken-link-action.pathoplexus.org/news/2024-09-12-two-weeks
https://preview-broken-link-action.pathoplexus.org/about/terms-of-use/data-use-terms
	404	http://www.pathoplexus.org
https://preview-broken-link-action.pathoplexus.org/about/terms-of-use/privacy-policy
	404	http://www.pathoplexus.org
https://preview-broken-link-action.pathoplexus.org/about/terms-of-use/terms-of-service
	404	http://www.pathoplexus.org
https://preview-broken-link-action.pathoplexus.org/about/governance/minutes
	404	https://preview-broken-link-action.pathoplexus.org/about/governance/minutes/2024-0[8](https://github.com/pathoplexus/pathoplexus/actions/runs/10864791460/job/30150482608?pr=134#step:4:9)-12_GAmeeting.pdf
https://preview-broken-link-action.pathoplexus.org/about/governance/data-submission
	404	http://www.pathoplexus.org/
```

### PR DESCRIPTION
**Pull request by corneliusroemer**
Resolves #136 
Resolves #133 

Uses https://github.com/raviqqe/muffet under the hood.

You can run the checks locally like this:

```
muffet "https://pathoplexus.org/" --buffer-size=8192 --accepted-status-codes="200..300,403,429" --rate-limit=20 --max-connections=10
```

Also refactors the news excerpts page to make the type of broken link bug less likely in future and generally makes that page easier to maintain into the future.

### CODE REVIEW

**Comment by theosanderson** [comment]
This is cool and something I have thought about for a while too. But I wonder about integrating it into the E2E type set up and making it self-contained rather than relying on preview instances. But this could be the starting point in any case.

**Comment by corneliusroemer** [comment]
Yeah it would be cool to have a test container as part of our preview deployments - or alternatively do this kind of stuff in a Github action k3d E2E thing.

**Comment by corneliusroemer** [comment]
Woopsie :D 

image

**Comment by theosanderson** [comment]
Ah, will need to look into www again

**Comment by corneliusroemer** [comment]
Looks like Science doesn't like our user agent (curl) - will use something more generic

```
*** INFO: [2024-09-14 18:10:14] Start checking: "https://preview-broken-link-action.pathoplexus.org/"
https://preview-broken-link-action.pathoplexus.org/about/faq
	403	https://www.niaid.nih.gov/
https://preview-broken-link-action.pathoplexus.org/news
	404	https://preview-broken-link-action.pathoplexus.org/news/2024-09-12-two-weeks
https://preview-broken-link-action.pathoplexus.org/about/terms-of-use/data-use-terms
	404	http://www.pathoplexus.org
https://preview-broken-link-action.pathoplexus.org/about/governance/minutes
	404	https://preview-broken-link-action.pathoplexus.org/about/governance/minutes/2024-0[8](https://github.com/pathoplexus/pathoplexus/actions/runs/10864492671/job/30149835249#step:5:9)-12_GAmeeting.pdf
https://preview-broken-link-action.pathoplexus.org/about/terms-of-use/terms-of-service
	404	http://www.pathoplexus.org
https://preview-broken-link-action.pathoplexus.org/about/terms-of-use/privacy-policy
	404	http://www.pathoplexus.org
https://preview-broken-link-action.pathoplexus.org/about/governance/data-submission
	404	http://www.pathoplexus.org
https://preview-broken-link-action.pathoplexus.org/news/2024-0[9](https://github.com/pathoplexus/pathoplexus/actions/runs/10864492671/job/30149835249#step:5:10)-13-two-weeks
	403	https://www.science.org/content/article/new-scientist-run-virus-database-vows-be-transparently-run-and-simple-use
*** ERROR: [2024-09-14 18:12:[11](https://github.com/pathoplexus/pathoplexus/actions/runs/10864492671/job/30149835249#step:5:12)] Something went wrong - see the errors above...
```

**Comment by corneliusroemer** [comment]
Ready for review @theosanderson  :) 

It now runs daily in ci on main, demo, staging, production

And on pull requests with preview.

**Comment by corneliusroemer** [comment]
Once merged, deploy main -> staging -> production to fix the links (in particular the lack of founding meeting minutes and the news excerpt "read more" links are critical)

**Review by chaoran-chen — COMMENTED** [review]
Thanks Cornelius! Could we maybe split the broken-link-checker and the link fixes into two PRs? The second one is easy to review and I can check and approve quickly. The first one is more difficult and I won't be able to review right away.

**Comment by corneliusroemer** [comment]
You mean the actions file? it doesn't really need review, worst case it fails but that's not causing any real harm. I don't expect you to review it, just wave through is fine.

**Review by theosanderson — APPROVED** [review]
I think I am comfortable with the broken link checker like this - we can still change it later

**Comment by theosanderson** [comment]
(My review isn't triggered by Chaoran's - I just got back to a computer at last :) )

**Comment by chaoran-chen** [comment]
> I don't expect you to review it, just wave through is fine.

I prefer not doing that but it's great that Theo can approve!

**Pull request merged**
